In [41]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [42]:
test_data = [[1,2,3,4],
             [5,6,8,6,9,2],
             [55,669,5,8,82,82,2],
             [9,58]]

In [43]:
pad_sequences(test_data)

array([[  0,   0,   0,   1,   2,   3,   4],
       [  0,   5,   6,   8,   6,   9,   2],
       [ 55, 669,   5,   8,  82,  82,   2],
       [  0,   0,   0,   0,   0,   9,  58]])

In [44]:
pad_sequences(test_data,padding='post',maxlen=5)

array([[ 1,  2,  3,  4,  0],
       [ 6,  8,  6,  9,  2],
       [ 5,  8, 82, 82,  2],
       [ 9, 58,  0,  0,  0]])

In [45]:
pad_sequences(test_data,padding='post',maxlen=5, truncating='post')


array([[  1,   2,   3,   4,   0],
       [  5,   6,   8,   6,   9],
       [ 55, 669,   5,   8,  82],
       [  9,  58,   0,   0,   0]])

In [46]:
pad_sequences(test_data,padding='post',maxlen=5, truncating='post', value = 1000)


array([[   1,    2,    3,    4, 1000],
       [   5,    6,    8,    6,    9],
       [  55,  669,    5,    8,   82],
       [   9,   58, 1000, 1000, 1000]])

### Lab Sequence modelling

In [47]:
from tensorflow.keras.datasets import imdb
(x_train, y_train),( x_test, y_test) = imdb.load_data()

<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
D:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\datasets\imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
D:\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\datasets\imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do

In [48]:
x_train.shape, y_train.shape

((25000,), (25000,))

In [49]:
print(f"Let's print first example {x_train[0]}")

Let's print first example [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [50]:
imdb_word_to_index = imdb.get_word_index()

In [51]:
imdb_index_to_word = {key[1]:key[0] for key in list(imdb_word_to_index.items())}

In [52]:
# Visualize first example
def get_example_from_index(example):
    return " ".join([imdb_index_to_word[i] for i in example])

In [53]:
get_example_from_index(x_train[0])


"the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but pratfalls to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other tricky in of seen over landed for anyone of gilmore's br show's to whether from than out themselves history he name half some br of 'n odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but wh

## Create padding to training examples

In [54]:
padded_x_train = pad_sequences(x_train, maxlen=300, padding='post', truncating='post')

## Create Masking layer

In [55]:
padding_x_train = np.expand_dims(padded_x_train, -1)
padding_x_train.shape

(25000, 300, 1)

In [60]:
import tensorflow as tf
tf_x_train = tf.convert_to_tensor(padding_x_train, dtype='float32')
masking_layer = tf.keras.layers.Masking(mask_value=0.0)(tf_x_train)

In [61]:
masking_layer._keras_mask


<tf.Tensor: shape=(25000, 300), dtype=bool, numpy=
array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])>